client: "127.0.0.1:0"

server: "127.0.0.1:8443"

# notice how we represent an embedded struct in YAML - with tab
timing:
  delay: "5s"
  jitter: 50

# add fields + values for protocol, tls_key, and tls_cert
